---
  - hosts: bigip
    collections: 
    - f5networks.f5_modules.bigip_device_info
    connection: local
     
    tasks:
      - name: Collect all BIG-IP information
        f5networks.f5_modules.bigip_device_info:
          gather_subset:
          - management-routes
        delegate_to: localhost
        register: out

      - name: Display the results
        debug:
          var: out

      - name: Collect all BIG-IP information
        f5networks.f5_modules.bigip_device_info:
          gather_subset:
          - management-routes
        delegate_to: localhost
        register: out2

      - name: Display the results
        debug:
          var: out2
