---
  - hosts: bigip
    connection: local

    vars:
      BIGIP1:
        server: 'BIGIP1.jennylabs.net'
        server_port: 443
        user: 'admin'
        password: '1Jcithof!'
        validate_certs: false
        no_f5_teem: true

      BIGIP2:
        server: 'BIGIP2.jennylabs.net'
        server_port: 443
        user: 'admin'
        password: '1Jcithof!'
        validate_certs: false
        no_f5_teem: true
     
    tasks:
      - name: Collect all BIG-IP information
        f5networks.f5_modules.bigip_device_info:
          gather_subset:
          - management-routes
          - remote-syslog 
          - sync-status 
          provider: "{{ BIGIP1 }}"
        delegate_to: localhost
        register: out

      - name: Display the results
        debug:
          var: out
          
      - name: Get failover state
        bigip_command:
           commands: 
             - "tmsh show sys failover"
        register: failover_state

      - name: Display Failover state
        debug:
          var: failover_state

      - name: Collect all BIG-IP information
        f5networks.f5_modules.bigip_device_info:
          gather_subset:
          - management-routes
          - remote-syslog 
          - sync-status
          provider: "{{ BIGIP2 }}"
        delegate_to: localhost
        register: out2

      - name: Display the results
        debug:
          var: out2
          
      - name: Get failover state
        bigip_command:
          commands:
            - "tmsh show sys failover" 
        register: failover_state_2

      - name: Display Failover state
        debug:
          var: failover_state_2
